### ISSUE TITLE
Event should be marked as favorite when signing up for this event

### ISSUE THREAD

**Issue by liseph** [webkom/lego#1266]

**Comment by kotlarz** [comment]
We don't have favorite function like we did in NERD as far as I know? The "star" next to the even title is only used to _pin_ events to the front page.

**Comment by edvardvb** [comment]
I dont think the star does anything right now. The backend supports following/favoriting events afaik

**Comment by kotlarz** [comment]
My bad, seems like we do indeed have a follow function (for users and events too!), I just got too caught on the "favorite" name instead of "follow". I'll get this fixed within today :smile:

**Comment by SmithPeder** [comment]
Yehh I think so
