### ISSUE TITLE
Could not book table at Lyche #Hacktoberfest

### ISSUE THREAD

**Issue by Chaaarles** [webkom/lego#1284]
**Expected behavior:**
Webkom should order table at Lyche

**Actual behavior:**
 They used bad rhetoric to make Dotkom do it

**Proposed fix:**
Webkom books a table for ca. max 15 Dotkompiser and all Webkommies

**Screenshots if applicable:**

![image](https://user-images.githubusercontent.com/17146935/46434967-7098a680-c755-11e8-9f3f-b81b339e7c9e.png)

![image](https://user-images.githubusercontent.com/17146935/46434810-01bb4d80-c755-11e8-8aa5-5e417f7b2081.png)

**Comment by SmithPeder** [comment]
Did you write this comeback in your native language

![46434810-01bb4d80-c755-11e8-8aa5-5e417f7b2081](https://user-images.githubusercontent.com/23152018/46435878-bce4e600-c757-11e8-963f-b7286220817a.png)

**Comment by SmithPeder** [comment]
> When you try to recover after forgetting key information

![screenshot from 2018-10-03 22-26-56](https://user-images.githubusercontent.com/23152018/46437353-772a1c80-c75b-11e8-97ae-e7bc49695d63.png)

**Comment by Chaaarles** [comment]
![webkomarebadandgay](https://user-images.githubusercontent.com/17146935/46437471-be181200-c75b-11e8-8c3b-50d7d7545023.png)

**Comment by SmithPeder** [comment]
> When the enemy surrenders, but you already spent a lot of time making this meme

![screenshot from 2018-09-23 23-09-46](https://user-images.githubusercontent.com/23152018/46437603-05060780-c75c-11e8-820b-2a37c8fa9b64.png)

**Comment by SmithPeder** [comment]
Men fint at dere fikser bord <3

**Comment by Chaaarles** [comment]
### Fixed
