### ISSUE TITLE
Download zip with highres logos

### ISSUE THREAD

**Issue by estensen** [webkom/lego#1311]
I want to have a button that downloads a zip with the logos on `abakus.no/brand`

The zip is ~1.3MB. Should I bundle it with `assets` or do you have a better system for slightly larger files like an S3 bucket?

**Comment by estensen** [comment]
Zip file: https://www.dropbox.com/s/pr8wu5j5r4vwww2/abakus-logoer.zip?dl=0

**Comment by odinuge** [comment]
We use S3 (hosted by AWS) for images, but we don't have a generic and simple upload util. What about using this repo: https://github.com/abakus-ntnu/grafisk-profil ? :thinking: The old stuff inside it looks outdated, and having version control on important assets isn't a stupid idea in my opinion..

Any thoughts?

**Comment by estensen** [comment]
I don't think the logo is changing anytime soon, so it's not strictly necessary to put in version control. But it does provide backup... I'll upload all important assets to `/grafisk-profil`

I think an S3 bucket is the simplest option. I'll just host the files in Dropbox until you have time to upload them. No rush!

Is an upload util on the roadmap?

**Comment by odinuge** [comment]
Smooth!

The upload util has a low priority, so using Dropbox, Google Drive etc. is the main solution atm. If we want a downloadable zip, we can just use this link: https://github.com/abakus-ntnu/grafisk-profil/archive/master.zip
