### ISSUE TITLE
Duplicate-event knapp

### ISSUE THREAD

**Issue by ingridkindem** [webkom/lego#1355]
Kan dere lage en knapp som gjør at man kan duplisere eventer, altså at man bruker et gammelt event som utgangspunkt når man skal lage et nytt arrangement? Hadde vært supersmud <3 Hilsen LaBamba

**Comment by SmithPeder** [comment]
This should be very possible. We could do something like this:
<img width="353" alt="screenshot 2019-01-27 at 14 50 30" src="https://user-images.githubusercontent.com/23152018/51801821-05fb0180-2243-11e9-8fea-67d48c3c512e.png">
, where you can generate a new event while looking at another event.

Or we could create a selector like the one used when generation 'Prikker', where you select the event you want to copy.
<img width="409" alt="screenshot 2019-01-27 at 14 53 10" src="https://user-images.githubusercontent.com/23152018/51801847-5b371300-2243-11e9-9982-11d956918840.png">

**Comment by ingridkindem** [comment]
Mest fan av den øverste løsningen, men så lenge det finnes noe så blir jeg glad

**Comment by JonasBak** [comment]
Fixed in https://github.com/webkom/lego-webapp/pull/1422
