### ISSUE TITLE
Duplikater av logoer på profil

### ISSUE THREAD

**Issue by asnestige** [webkom/lego#1360]
Heihei,
Jeg har fått PR-logoen tre ganger på profilen min (2017-2018, 2018-2019 og 2019-d.d.), er det mulig å få samlet disse til en, det gjelder også mange andre? 

I tillegg har jeg meldt meg inn og ut av litt interessegrupper og alle disse har kommet opp som grå bortover på profilen. Er det nødvendig at de blir grå, da interessegrupper liksom ikke er noe man "slutter i" men kanskje heller møter opp litt av og på? 

_Beklager rart formulert issue, og at det ikke står på engelsk :-)_

**Comment by cherrybeans** [comment]
Forslag: Bruker kan selv gå inn å administrere hva som vises på profilen sin av badges, og kanskje slette det man ikke vil ha lengre.
