### ISSUE TITLE
Switch to babel 7

### ISSUE THREAD

**Issue by odinuge** [webkom/lego#1370]
```
return (<> <p /> <p /> </>);
```

**Comment by JonasBak** [comment]
[Maybe useful](https://babeljs.io/docs/en/v7-migration)

**Comment by odinuge** [comment]
Fixed in https://github.com/webkom/lego-webapps/pulls/1442, https://github.com/webkom/lego-webapps/pulls/1469, https://github.com/webkom/lego-webapps/pulls/1472, https://github.com/webkom/lego-webapps/pulls/1473 & https://github.com/webkom/lego-webapps/pulls/1474 :fire:
