### ISSUE TITLE
Switch to webpack 4

### ISSUE THREAD

**Issue by odinuge** [webkom/lego#1371]

**Comment by JonasBak** [comment]
[This might help (a bit)](https://webpack.js.org/migrate/4/)

**Comment by odinuge** [comment]
Fixed in https://github.com/webkom/lego-webapps/pulls/1442, https://github.com/webkom/lego-webapps/pulls/1469, https://github.com/webkom/lego-webapps/pulls/1472, https://github.com/webkom/lego-webapps/pulls/1473 & https://github.com/webkom/lego-webapps/pulls/1474 :fire:
