### ISSUE TITLE
User verification page

### ISSUE THREAD

**Issue by odinuge** [webkom/lego#1373]
Create a clone of abacard, for user verification. Should only check if the user is active, and do nothing more.

Maybe add a group filter, so only users in a certain group(s) are accepted. :smile: 

Useful on events without registration that still need verification, eg. genfors.

PS: Can be separated from LEGO. It doesn't really matter

**Comment by kotlarz** [comment]
Closed by https://github.com/webkom/lego-webapp/pull/1443
