### ISSUE TITLE
"Registration open" when it's not

### ISSUE THREAD

**Issue by estensen** [webkom/lego#1378]
All events in https://abakus.no/events are labeled as "Påmelding åpen!", even when they're more than a week away

<img width="1058" alt="screenshot 2019-01-30 14 57 55" src="https://user-images.githubusercontent.com/9142800/51986002-80c05880-249f-11e9-80cf-8c31ee46a1c8.png">

**Comment by vhellem** [comment]
Would it not be possible to use the events totalCapacity field? Or would that make it look weird for events that are open but do not actually have a registration?

**Comment by SmithPeder** [comment]
Not really fixed yet tho. But now we have the fields we need to create a good implementation for this.
