### ISSUE TITLE
Update to redux-form v8

### ISSUE THREAD

**Issue by odinuge** [webkom/lego#1423]
`Redux-form` v7 adds proper flow support (no idea why the things we do doesn't crash flow... :laughing:). 

We have to rewrite some small stuff, and add a hugo about of `$FlowFixMe:
```jsx
import { FormProps } from 'redux-form'; // from this
import { type FormProps } from 'redux-form'; // to this
```

We currently use `redux-form v6.8`.

**Comment by mrfarstad** [comment]
FYI: redux-form v8 requires react-redux v6, which breaks many used packages

**Comment by LudvigHz** [comment]
Fixed in https://github.com/webkom/lego-webapp/pull/1550
