### ISSUE TITLE
Replace the "Undergrupper" page with something more dynamic

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego#1437]
![screenshot from 2018-01-21 16-30-44](https://user-images.githubusercontent.com/23152018/35195767-8bdab92a-fec8-11e7-9835-7fb0b91ec4fd.png)

**Comment by orhanhenrik** [comment]
This is fixed with new about pages, right?

**Comment by cherrybeans** [comment]
It's not dynamic, but it does not look bad either.

**Comment by orhanhenrik** [comment]
Since there are so few and they rarely change, I don't think it's worth the time to make this dynamic.

**Comment by cherrybeans** [comment]
Agreed
