### ISSUE TITLE
Add MazeMap integration

### ISSUE THREAD

**Issue by odinuge** [webkom/lego#1446]
It would be awesome with MazeMap support. When adding a location to an event/meeting, the user can either choose a normal text value, or choose campus and room. We can then link locations to Mazemap.

We would only need to store a `positionId` called `poiId`, together with the name of the room/space.

What do people think about this?

Docs: [API-docs](https://www.mazemap.com/developer-api)

**Comment by henrikforb** [comment]
That would have been great.

**Comment by eikhr** [comment]
Done in #2443 and [#2383 in webapp](https://github.com/webkom/lego-webapp/pull/2383)
