### ISSUE TITLE
On mobile, decrease height of pictures in articles 

### ISSUE THREAD

**Issue by cherrybeans** [webkom/lego#1459]
If you have a landscape picture in a article and view it on mobile, the image takes up the entire screen, with lots of empty space over and under the image.

**Comment by tmsolber** [comment]
Looks ok on my phone?

**Comment by cherrybeans** [comment]
It doesn't look like this?
![Screenshot from 2019-03-11 19-56-27](https://user-images.githubusercontent.com/25204035/54150036-d6413b00-4437-11e9-8c50-e8156f80572c.png)

**Comment by tmsolber** [comment]
Yes it does, thought you meant the title picture.
