### ISSUE TITLE
About Abakus issues dump

### ISSUE THREAD

**Issue by cherrybeans** [webkom/lego#1461]
These images show screenshots of issues that should be fixed and notes (with varying priority etc). 

![dadkkwpogjka](https://user-images.githubusercontent.com/25204035/53279837-26b85900-3714-11e9-9fb0-6a375961c68d.png)
Sidebar not fixed width.

**Comment by orhanhenrik** [comment]
Is anybody looking into these issues? Should we split it up into smaller issues? @cherrybeans
