### ISSUE TITLE
Export data from survey

### ISSUE THREAD

**Issue by cherrybeans** [webkom/lego#1462]
Talking with a bedkommer, it came up that today they manually export the data from the surveys into e.g. excel for the reports they give to the companies, and that companies don't see the graphs you generate from surveys on abakus.no for various reasons.

They would like an export to csv option (or some format) to be able to do this easier.

**Comment by SmithPeder** [comment]
Related to #1395

**Comment by iselinee** [comment]
Solved in https://github.com/webkom/lego-webapp/pull/1570
