### ISSUE TITLE
Undefined event capacity

### ISSUE THREAD

**Issue by odinuge** [webkom/lego#1468]
`65/undefined === NaN` :cry: 

![screenshot from 2019-02-27 12-43-29](https://user-images.githubusercontent.com/1467188/53488004-5b6a3e80-3a8d-11e9-9394-ed4283e65542.png)

**Comment by orhanhenrik** [comment]
Related to #1488 ?

**Comment by kotlarz** [comment]
This should be fixed now that #1512 is merged @SmithPeder?

**Comment by SmithPeder** [comment]
NoNo. all our work does nothing. All it does is add a new field! Both the `overview` frontpage and the `eventlist` need to be rewritten use these new fields.

**Comment by SmithPeder** [comment]
Fixed in https://github.com/webkom/lego-webapp/pull/1519
