### ISSUE TITLE
Kan ikke legge til bilde i arrangementstekst til tross for ikon som indikerer at det er mulig

### ISSUE THREAD

**Issue by simoneby** [webkom/lego#1469]
![screenshot 2019-02-28 at 12 12 04](https://user-images.githubusercontent.com/16305584/53562767-8cf90d80-3b52-11e9-9b0f-39caa2ceb193.png)

**Comment by odinuge** [comment]
Hei! Tusen takk for beskjed, skal se på det så fort som mulig!

**Comment by orhanhenrik** [comment]
@simoneby kan du beskrive mer om hva som ikke fungerer? Er det knappen som ikke er klikkbar, eller skjer det en feil når du forsøker å laste opp bildet?  
Hvilken nettleserversjon og operativsystem bruker du?

**Comment by simoneby** [comment]
Jeg skrev issuet på vegne av PR ansvarlig i komiteen så usikker på om det
gjelder flere nettlesere, men gjelder hvertfall safari. Begge bruker Mac.
Knappen er ikke klikkbar, ble oppdaget når hun prøvde å legge inn bilde i
arrangementstekst.

fre. 1. mar. 2019 kl. 10:18 skrev Orhan Hirsch <notifications@github.com>:

**Comment by orhanhenrik** [comment]
Takk! Jeg ser at det ikke fungerer i Safari ja, dette skal vi få fikset.  
Som en midlertidig løsning kan dere bruke chrome eller firefox, da det ser ut til å fungere i begge disse nettleserene.
