### ISSUE TITLE
Interestgroups styling

### ISSUE THREAD

**Issue by odinuge** [webkom/lego#1478]
![screenshot from 2019-03-06 10-06-03](https://user-images.githubusercontent.com/1467188/53868982-860d4780-3ff7-11e9-9b98-cacb841ac6dc.png)

**Comment by JonasBak** [comment]
:muscle: :muscle: :muscle: :muscle: :muscle:

**Comment by cherrybeans** [comment]
I don't see the problem :thinking:

**Comment by mrfarstad** [comment]
I think the biceps is just too large for the div to contain

**Comment by cherrybeans** [comment]
This is not reddit

**Comment by odinuge** [comment]
> I don't see the problem :thinking:
> @cherrybeans 

Maybe that is the problem :thinking:
