### ISSUE TITLE
Henting av hendelse følgere feilet

### ISSUE THREAD

**Issue by NikZy** [webkom/lego#1481]
Hvis du prøver å legge et arrangement til favoritter, deretter fjerner det fra favoritter igjen og refresher siden.

# Expected Behavior
Ingen skummel feilmelding når jeg refresher

# Current Behavior
Skummel feilmelding når jeg refresher:
> Henting av hendelse følgere feilet

# Failure Information (for bugs)
Eksempel:
![bilde](https://user-images.githubusercontent.com/5860069/53976025-72043b80-4106-11e9-86f4-adc4aa26f902.png)

## Steps to Reproduce
1. Legg et arrangement til favoritter
2. Fjern det fra favoritter
3. Refresh
Feilmeldingen dukker opp hver gang du refresher i en stund (usikker hvor lenge).

## Context
* Nettleser: Firefox Quantum 65.0.2 (64-bits)
* Win 10 Pro
* Addons til firefox: uBlock Origin, HTTPSEverywhere, Disconnect

## Failure Logs
Feilmelding fra console:
`Unhandled promise rejection Object { type: "Event.IS_USER_FOLLOWING.FAILURE", payload: Error, error: true, meta: {…} } vendors~app.chunk.19c5fb19.js:48:956126
	e https://abakus.no/vendors~app.chunk.19c5fb19.js:48
	e https://abakus.no/vendors~app.chunk.19c5fb19.js:38
	exports https://abakus.no/vendors~app.chunk.19c5fb19.js:38
	E https://abakus.no/vendors~app.chunk.19c5fb19.js:38
	exports https://abakus.no/vendors~app.chunk.19c5fb19.js:38
	<anonymous> https://abakus.no/vendors~app.chunk.19c5fb19.js:38
	A https://abakus.no/vendors~app.chunk.19c5fb19.js:38
	q https://abakus.no/vendors~app.chunk.19c5fb19.js:38
`

**Comment by JonasBak** [comment]
Fixed in https://github.com/webkom/lego-webapp/pull/1480
