### ISSUE TITLE
Registrering av interesse feilet

### ISSUE THREAD

**Issue by NikZy** [webkom/lego#1482]
Hvis du melder deg på et arrangement, deretter prøver å legge det til som favoritt får du en feilmelding.

# Expected Behavior
Arrangementet blir lagt til som favoritt.

# Current Behavior
Arrangementet blir IKKE lagt til som favoritt og det dukker opp en skummel feilmelding.

> Registrering av interesse feilet

# Failure Information (for bugs)
Eksempel:
![bilde](https://user-images.githubusercontent.com/5860069/53976295-05d60780-4107-11e9-9bb9-655595166cca.png)

## Steps to Reproduce
1. Meld deg på et arrangement
2. Legg arrangementet til som favoritt rett etterpå

## Context
* Nettleser: Firefox Quantum 65.0.2 (64-bits). Vet det skjer i Chrome på mobilen også
* Win 10 Pro
* Addons til firefox: uBlock Origin, HTTPSEverywhere, Disconnect

## Failure Logs
`Unhandled promise rejection {…}​error: true​meta: Object { errorMessage: "Registering av interesse feilet", optimisticId: 94511668355277, endpoint: "/followers-event/", … }​payload: Error: "HTTP 409"
	r https://abakus.no/app.24a50991.js:1
	t https://abakus.no/app.24a50991.js:1
	b https://abakus.no/app.24a50991.js:1
​type: "Event.FOLLOW.FAILURE"​<prototype>: Object { … } vendors~app.chunk.19c5fb19.js:48:956126
`

**Comment by odinuge** [comment]
Hei!

Det har vi ikke tenkt på! Det har seg nemlig sånn at når man registrerer seg, favoriseres arrangementet automatisk; men, det skjer uten at det ser sånn ut for brukeren. Derfor krasjer det når man prøver å trykke favoriser (siden man allerede har markert den som favoritt).


Good catch, og takk for tilbakemelding. :ok_hand:

**Comment by odinuge** [comment]
Denne er fikset i https://github.com/webkom/lego-webapp/pull/1537! Skal være ute på abakus.no ila. dagen! :tada:
