### ISSUE TITLE
Radio buttons på brukerprofil går over teksten

### ISSUE THREAD

**Issue by NikZy** [webkom/lego#1483]
![bilde](https://user-images.githubusercontent.com/5860069/53977883-471be680-410a-11e9-8fa3-df8b4c859c21.png)

**Comment by iselinee** [comment]
Which browser and what device are you using?

**Comment by NikZy** [comment]
Nettleser: Firefox Quantum 65.0.2 (64-bits). Vet det skjer i Chrome på mobilen også
    Win 10 Pro
    Addons til firefox: uBlock Origin, HTTPSEverywhere, Disconnect
