### ISSUE TITLE
Kan ikke åpne/se arrangementer på mobil

### ISSUE THREAD

**Issue by simoneby** [webkom/lego#1490]
Kan ikke trykke meg inn på arrangementer på telefon, kommer bare videre til blank side :( bruker safari på iPhone 7

**Comment by orhanhenrik** [comment]
Kan du ta et skjermbilde av denne blanke siden du kommer til? Hva er URLen i menybaren når du får den blanke siden?

**Comment by simoneby** [comment]
Slik ser det ut

ons. 13. mar. 2019 kl. 19:57 skrev Orhan Hirsch <notifications@github.com>:

**Comment by orhanhenrik** [comment]
Hei, vedlegget kommer ikke med når du sender det som mail. Prøv å gå inn på https://github.com/webkom/lego/issues/1490 for å laste det opp 👍
