### ISSUE TITLE
Empty polls header on frontpage

### ISSUE THREAD

**Issue by JonasBak** [webkom/lego#1491]
When there is no active polls on the frontpage, there is just an empty header over readme.

![polls bug](https://user-images.githubusercontent.com/16608915/54187228-5bb30280-44ad-11e9-8405-e67443dd2819.png)

**Comment by SmithPeder** [comment]
I fixed this in https://github.com/webkom/lego-webapp/pull/1519 for `polls` and other sections on the frontpage, not knowing it was an issue with someone assigned. Sorry :/
