### ISSUE TITLE
Logger ut på mobilen hvis man trykker på poll

### ISSUE THREAD

**Issue by asnestige** [webkom/lego#1498]
Hvis jeg trykker på pollen inne på Abakus.no på mobilen kommer det en loading-screen opp som ikke går vekk og meldingen "Henting av avstemning feilet". Om jeg da trykker på f.eks logoen eller refresher siden er jeg blitt logget ut av abakus.no. Testet flere ganger og det skjedde igjen, men skjer ikke på pc.

**Comment by odinuge** [comment]
Should be fixed in https://github.com/webkom/lego/pull/1497. :taco:

**Comment by kotlarz** [comment]
Fixed in #1497.
