### ISSUE TITLE
Inconsistent ordering of answers

### ISSUE THREAD

**Issue by estensen** [webkom/lego#1513]
For the quiz I got after attending the Visma course I got some answering options that were not ordered:

<img width="523" alt="Screenshot 2019-03-20 09 39 35" src="https://user-images.githubusercontent.com/9142800/54671130-8fb5a580-4af5-11e9-8abd-c1c4a076ead4.png">

**Comment by ivarnakken** [comment]
Closing issue as these bad orderings seems to be the result of user errors, and not bad code. Will keep an eye out for it in the future though.
