### ISSUE TITLE
Move frontend codebase to TypeScript

### ISSUE THREAD

**Issue by orhanhenrik** [webkom/lego#1519]

**Comment by SmithPeder** [comment]
### Discussion 

I have started a little on this with some quick changes to babel and so forth but I think we should have a little (read large) discussion about how we want to do this. 

There are a lot of alterations that can be done regarding the `tsconfig.json`, so figuring out what we want, and what we don't want might be clever to do.

There is also a method of "how" to migrate. I was thinking we would use some **Incremental Migration** tactic where `.js` and `.ts` files coexist in the project. Then every .js file is read by the `@babel/preset-flow` and all `.ts` files are read by the `@babel/preset-typescript`. This way we can create a new `models.ts` and type create good types from the gecko and type each file one by one. Then when the last `@flow` typing is gone we can remove all of the flow.

The other method would be changing all the types in `models.js -> models.ts` then changing the rest of the files in a big batch. Knowing webkom, this might take a long time, and all work done in this period will result in massive merge-conflicts.

I'm a fan of the first option, where we merge a `ts` config with new and improved typing, then fix large parts of the webapp(where nobody is working right now) project in batches.

Maybe we can discuss this at the next meeting? @JonasBak @odinuge

**Comment by odinuge** [comment]
Yeah. Flow is dying, and ts is the way to go :tm: 

Your plan sounds good @SmithPeder, but we should also look at why we use flow, how we use it and what doesn't work today. Imo. the biggest problem isn't flow itself (but yes, we should definitely switch) but more how we use it. We only use it in components and the "consumers" of data. Our redux-state, actions, reducers and routes (when mapping state and actions to the components) have more or less 0% real coverage. Some files have typings, but we have no idea if they makes sense or not.

A smooth transition is nice, but we should make a plan on how to get "`100%`" coverage, else we will end up with just switching file extensions without getting any real benefits.

**Comment by orhanhenrik** [comment]
I agree that we should aim for 100% coverage. I also agree that a smooth transition is nice, but I’m not sure how feasible it is. Either way it will require a lot of work to migrate the existing code and to add types everywhere.  

I think that more and better typing along with end to end testing will improve quality of our codebase a lot and will make it easier to trust that pull requests won’t break anything.
