### ISSUE TITLE
Cannot unregister from event if unanswered surveys

### ISSUE THREAD

**Issue by vhellem** [webkom/lego#1523]
If you want to unregister from an event, you have to answer all unanswered surveys first, this should only happen when you want to register for an event. 

<img width="1117" alt="Screenshot 2019-03-25 at 09 14 09" src="https://user-images.githubusercontent.com/9450684/54904312-75f1d500-4ede-11e9-93ca-0df722818613.png">

**Comment by ivarnakken** [comment]
Resolved by https://github.com/webkom/lego-webapp/pull/3284
