### ISSUE TITLE
Search in menu should not autofocus on mobile

### ISSUE THREAD

**Issue by orhanhenrik** [webkom/lego#1531]
The keyboard on mobile makes the autofocusing of search very annoying. I believe most people use the menu items rather than search as well.

Here is a screenshot from my iPhone X, which is a very tall phone (so it is even worse on other phones)
![IMG_1CE6E14E5A5F-1](https://user-images.githubusercontent.com/5272089/55158032-376a4d80-515e-11e9-928f-02e20d981127.jpeg)

**Comment by eikhr** [comment]
This has been fixed
