### ISSUE TITLE
Menu on mobile has strange scroll behavior

### ISSUE THREAD

**Issue by orhanhenrik** [webkom/lego#1532]
I'm on iOS, and there are two scrollable areas in the menu, one is scrolling the page, and one is scrolling a scroll view that contains the menu items. Scrolling in the menu does not feel like native search and is slow (it does not get intertia like other iOS scrolling)

![out](https://user-images.githubusercontent.com/5272089/55158801-0854db80-5160-11e9-887c-1267d8539834.gif)

**Comment by eikhr** [comment]
Seems to work now
