### ISSUE TITLE
Polls allows blank answers when editing

### ISSUE THREAD

**Issue by orhanhenrik** [webkom/lego#1534]
If you edit a poll -> add new choice -> submit, the blank answer will be added to the poll. You can also delete existing answers and only add blanks.

Blank answers should be validated in both backend and frontend.

Example:
![image](https://user-images.githubusercontent.com/5272089/55176998-82965780-5182-11e9-96f4-9aeb22bbc24e.png)

**Comment by eikhr** [comment]
options are now validated in frontend (have not tested backend)
