### ISSUE TITLE
Meeting invitation with message

### ISSUE THREAD

**Issue by dennisjanzso** [webkom/lego#1538]
Hi. Is it possible to get a feature that allows me to create and send a message with meeting invitations. Right now I can send invitations, but the mail everyone receives is just a standard mail with a link to the 'event' on abakus.no. This is very good, but it would be great to be able to send a custom message with that mail. For instance I might want to tell people to have a look at something before the meeting, and it would be nice to be able to put this in the mail everyone receives. Can you make this happen?

**Comment by LudvigHz** [comment]
With #2035, we can add the description to the meeting invite, and that should be a good solution to this.

**Comment by ivarnakken** [comment]
Closing issue as this has been resolved with a `description`, like @LudvigHz says.
