### ISSUE TITLE
Add an alternative SearchBackend for dev and test

### ISSUE THREAD

**Issue by orhanhenrik** [webkom/lego#1542]
Add a new SearchBackend to lego that can be run in dev and test. With a new search backend we can stop using elasticsearch in dev and test, as it is very resource intensive. 

This will make e2e tests run faster/more stable and make running lego on a laptop a bit more friendly.

This will also help in e2e tests as the search index will be easier to reset between every test.

**Comment by edvardvb** [comment]
Was this fixed yesterday?

**Comment by orhanhenrik** [comment]
Yes!
