### ISSUE TITLE
React Router - React Redux update list

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego#1547]
# Dependencies

- [ ] Bump `react-router v.5`
https://www.npmjs.com/package/react-router 

- [ ] Change `react-router-redux` to `connected-react-router v.6.3.2` https://github.com/supasate/connected-react-router

`react-router-redux` is deprecated and cannot be used with `react-router v.5`, therefore we need to switch to the `connected...` that supports v4 and v5. `connected...` requires React Redux v6.0 or later.

- [ ] Bump `react-redux v.6` 
https://github.com/reduxjs/react-redux

- [ ] Bump `raven-for-redux v1.4` 
https://www.npmjs.com/package/raven-for-redux

- [ ] `react-router-scroll v0.4.4`
https://www.npmjs.com/package/react-router-scroll
 
Our version of redux-form uses outdated props from the old react-redux, so it has to be bumped as well

- [ ] Bump_ `redux` and peer deps
    `redux: ^3.7.2`,
    `redux-form: ^6.5.0`,
    `redux-logger: ^3.0.1`,
    `redux-segment: ^1.6.2`,
    `redux-thunk: ^2.2.0`

- [ ] Bump `redux-mock-store`
https://github.com/dmitry-zaets/redux-mock-store#redux-mock-store-

**Comment by LudvigHz** [comment]
Fixed in https://github.com/webkom/lego-webapp/pull/1550
