### ISSUE TITLE
Add purple as new color for event-type "alternativ bedpres"

### ISSUE THREAD

**Issue by regineru** [webkom/lego#1628]
It would be nice to have a separate color for "alternativt bedriftsarrangement/alternativ bedpres" to distinguish them from regular bedpres. Purple is nice if possible, but anything is fine.

**Comment by SmithPeder** [comment]
What would qualify as an **alternativt bedriftsarrangement**? I'm not familiar with this event-type 😄 

Do you want a new category for alternative bedpress, I always felt like the **lunsjpress** was the alternative version of a **bedpress**

The current categories are (_plus KID which could have been listed here_):
![image](https://user-images.githubusercontent.com/23152018/59983387-2d51d100-961f-11e9-91fd-73ce1d1fb0ae.png)

**Comment by regineru** [comment]
Yes, I want a new category: D Alternative bedriftsarrangementer are eg go-carts, full-day seminars, boat trips etc. (anything fun that the company comes up with). We have experienced some problems where the participants are not prepared for anything other than a presentation and dinner, so we want to convey more clearly that it is a more "fun" and different event. The only difference between lunsjpres and bedpres is the time of day, but here are different arrangements as well.

**Comment by odinuge** [comment]
`Alternativt bedriftsarrangement` (most fan of this term) or `Alternativ bedpres` sounds good! 👍 

Also, ref. the image, shouldn't the old `Bedpress` be `Bedpres`, from what I remember from my time in _HS_ 😅.

**Comment by regineru** [comment]
Yes Odin, that is correct

**Comment by odinuge** [comment]
If someone wants to fix it:

https://github.com/webkom/lego-webapp/blob/cb23565850022339e147f085cd753f42802a1c74/app/routes/events/components/EventFooter.js#L14
