### ISSUE TITLE
Migrate stripe to support SCA

### ISSUE THREAD

**Issue by JonasBak** [webkom/lego#1631]
We have use a [SCA](https://stripe.com/docs/strong-customer-authentication) compliant payment flow before September 14, 2019.

Stripe already has services and APIs ready, and instructions on migrating [here](https://stripe.com/docs/strong-customer-authentication/migration)

**Comment by LudvigHz** [comment]
What needs to be done:
- Upgrade our Stripe API version https://stripe.com/docs/upgrades#how-can-i-upgrade-my-api
- switch from the `token` API to the `paymentMethod` API (backend and frontend) https://stripe.com/docs/payments/payment-intents/migration
- migrate from the `charge` API to the new `intent` API
- migrate the Payment request button to use the new `intent` API https://stripe.com/docs/stripe-js/elements/payment-request-button#complete-payment-intents

**Comment by LudvigHz** [comment]
Fixed in #1669
