### ISSUE TITLE
Certain cypress tests are dependent on temporary data

### ISSUE THREAD

**Issue by mrfarstad** [webkom/lego#1703]
Some tests are depending on data which is only available in a certain time frame. This should be avoided.

**Comment by orhanhenrik** [comment]
Do you have an example?

**Comment by mrfarstad** [comment]
@orhanhenrik https://github.com/webkom/lego-webapp/commit/9c5dd050d0ba7ad696371c26e5482cb01bc96755

This test suddenly failed 🌵

**Comment by orhanhenrik** [comment]
Did we change ordering or fixtures on backend maybe? The tests start a fresh backend with fixtures, so that this suddenly failed is strange.

**Comment by odinuge** [comment]
> Did we change ordering or fixtures on backend maybe? 

Not the last 11 days.

I am pretty sure it is the famous for loop in `update_event_dates` https://github.com/webkom/lego/blob/master/lego/utils/management/commands/load_fixtures.py#L114-L124.
