### ISSUE TITLE
Add separate box for pinned articles on home page

### ISSUE THREAD

**Issue by Magssch** [webkom/lego#1709]
Currently, events and articles both share the same space on the home page when pinned, and thus events will always take precedence over articles when pinned. This is problematic when the amount of events is bountiful -- as all new articles are burried at the bottom of the page when events are pinned for long periods of time.

**`readme`** would like to therefore humbly request -- after correspondence with Jonas Bakken of Webkom as well as other members of the Board of Directors of Abakus -- that we add another, separate box for pinned articles which is positioned beneath the current box for pinned items. Thusly, the original box will only contain pinned events. 

In the case of no events being currently pinned, only one box should be present on the home page. In this case, it would assumedly be natural for the pinned box to show the latest article, or if any -- the latest _pinned_ article.

We would like to request this feature be added to both desktop and mobile view.

**Comment by odinuge** [comment]
Work in progress here: https://github.com/webkom/lego/pull/1302 & https://github.com/webkom/lego-webapp/pull/1351

**Comment by JonasBak** [comment]
Like this but without the second "Festet oppslag"?
![image (1)](https://user-images.githubusercontent.com/16608915/66857662-05003080-ef88-11e9-958a-7d6c17b28efb.png)

**Comment by Magssch** [comment]
Yes please! Alternatively, we could move the poll further down and put the pinned article to the right of events. I am unsure of who is using the polls and whether this will affect them heavily though.

**Comment by eikhr** [comment]
https://github.com/webkom/lego-webapp/pull/2697
