### ISSUE TITLE
Adjust styling for committees on about page

### ISSUE THREAD

**Issue by erlingfn** [webkom/lego#1711]
After being updated to the image component, the styling for the committee logos on the about abakus page has been broken. 
![image](https://user-images.githubusercontent.com/7977650/66868670-0a687580-ef9e-11e9-96a8-8a6a78d72b3b.png)

**Comment by JonasBak** [comment]
It's fixed, but not in prod: https://webapp-staging.abakus.no/pages/info-om-abakus

**Comment by SmithPeder** [comment]
`git pull && git push origin master:prod`

https://github.com/webkom/lego-webapp/commit/d9ea01b031552be3e489459d2ad4a1f40ca6c0df

![image](https://user-images.githubusercontent.com/23152018/66868804-54e9f200-ef9e-11e9-9d4d-7aeff2502a7f.png)
