### ISSUE TITLE
Email anchor links are "invisible"

### ISSUE THREAD

**Issue by kristianvld** [webkom/lego#1716]
Default links in emails are without text decoration and the same gray colour as normal plaintext, making them hard to detect.

Example survey reminder email, that I for the last couple of years didn't know had link directly to the survey:
<img width="646" alt="image" src="https://user-images.githubusercontent.com/7207116/67864419-e3757c00-fb25-11e9-9f17-e1374b27fae4.png">
(the text "Gå til undersøkelse" is a direct link to the survey)

**Comment by LudvigHz** [comment]
Fixed in #1717
