### ISSUE TITLE
Ability to upload pdf-files as headers to events.

### ISSUE THREAD

**Issue by wfeiring** [webkom/lego#1723]
Currently you are not able to upload cover-photos /headers as pdf-files to events. This results in lower quality, as the files has to be uploaded as png instead. It is possible to upload as svg, which is also a vector format, but there are som weird bugs with svg-exports with illustrator and photoshop.

**Comment by SmithPeder** [comment]
Being able to upload a `pdf` as a header for an event seam quite wired. 😕From my knowledge, it will be a large undertaking to create this feature. The backend has support for uploading all file formats, but the frontend image cropping component does not (and one would need to crop the `pdf` somehow), then it would need to be converted to some image format, like `svg`, to work properly with the image components.

Implementing this will be a bandage on the real solution which is :

> "but there are som weird bugs with svg-exports with illustrator and photoshop.

Exporting `svg` from photoshop and illustrator has always worked for me, but I don't use it a lot so I have less experience with bugs that might appear

**Comment by wfeiring** [comment]
Ah, that's fair then! I hoped that it would just be to allow an extra
file-format. I'm guessing .ai and .psd would be equally weird considering
the cropping. Also, just throwing ideas around, but could it be possible to
remove cropping from .pdf-files and only use them as-is, given that we use
the correct format (1100 x 330?)? 🤔
Honestly, png works just fine. If any implementation of this is a headache,
then it's not a priority or concern.

Lastly, I've attached two pictures, one .svg and one .pdf of the same
illustrator-file to illustrate the problem 🤔I'll go a little more in-depth
about SVG-exporting though, and see if I can find some tips or tricks to
help me out!

tor. 7. nov. 2019 kl. 13:19 skrev Peder Smith <notifications@github.com>:

**Comment by wfeiring** [comment]
Apparently attaching them while answering through Gmail doesn't work, so here they are: 
[komhjem2.pdf](https://github.com/webkom/lego/files/3819704/komhjem2.pdf)
![image](https://user-images.githubusercontent.com/22595827/68391040-f2cc7900-0166-11ea-9826-65c1094ddf68.png)

The last one is a screenshot of the SVG-one.

**Comment by SmithPeder** [comment]
So you have an .ai file and try to export it to both `svg` and `pdf`? Can you send me the `.ai` file?

**Comment by orhanhenrik** [comment]
The problem with PDFs are that they cannot be embedded natively in a webpage like you can with an image. We would need to use a PDF renderer which would render with scrollbars, zooming, etc.

If there is a bug in the svg export, you can try to use `pdf2svg` (https://github.com/dawbarton/pdf2svg), even though this is a bit of a hacky solution..


Attached is a screenshot of the svg, since github doesn't support svg..
![Screenshot 2019-11-07 at 14 46 40](https://user-images.githubusercontent.com/5272089/68394058-738e7380-016d-11ea-9b5f-ea5edf0e94ee.png)
File size is 504KB.

**Comment by wfeiring** [comment]
Perfect! I'll let the rest of the people in PR known.

Here is the .ai file in case you have any export hacks for me either way 🙌
[komhjem2.ai.zip](https://github.com/webkom/lego/files/3819982/komhjem2.ai.zip)
