### ISSUE TITLE
Forslag: gjem påmeldinger-modulen når det ikke er noen kommende påmeldinger

### ISSUE THREAD

**Issue by Magssch** [webkom/lego#1730]
Tar dette på norsk fordi jeg ikke finner en god oversettelse av "påmeldinger". Per nå har vi en stor del av forsiden som brukes kun til å vise "ingen påmeldinger de nærmeste 3 dagene". Selv om jeg ser verdien i å vise abakuler at det ikke er noe som skjer i nærmeste fremtid slik at man slipper å lete gjennom selv, så synes jeg det er enda viktigere at artikler, #weekly og lignende er så synlige som overhodet mulig. Foreslår derfor at "Påmeldinger"-boksen automatisk gjemmes når den ikke har noe innhold som vist på bildet, ettersom man da kan prioritere å vise viktig info som nå blir gjemt langt ned på siden.
<img width="1160" alt="Skjermbilde 2019-11-21 kl  11 18 08" src="https://user-images.githubusercontent.com/37403247/69329125-c4fc2f80-0c50-11ea-97e6-b52aa47c310b.png">

**Comment by Magssch** [comment]
No one agrees? :(

**Comment by Magssch** [comment]
Ingen som er enige her? :(

**Comment by SmithPeder** [comment]
😱

**Comment by SmithPeder** [comment]
Jeg er enig at det er ganske mye `free/prima real-estate` som brukes til å vise et **"ingenting skjer hos abakus"** 😢 Jeg kan gjøre noen quick endringer,  så kan vi se forslaget in action 👍

**Comment by Magssch** [comment]
Du er et beist Peder!! 

![bitmoji](https://render.bitstrips.com/v2/cpanel/cca85ed7-881b-4c03-bb66-294584e11e07-4d4357d4-32b3-492f-9d81-a850b638d8e3-v1.png?transparent=1&palette=1&width=246)
