### ISSUE TITLE
Using htmlcanvas.toBlob() breaks site in ms edge

### ISSUE THREAD

**Issue by erlingfn** [webkom/lego#1755]
The blob method for HTMLCanvasElement does not work for microsoft edge [ref](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob). This causes an error in [sentry](https://sentry.abakus.no/webkom/lego-webapp/issues/7843/?environment=production).

**Comment by kotlarz** [comment]
>MS Edge

🙅‍♂️🙅‍♂️🙅‍♂️

**Comment by LudvigHz** [comment]
Fixed in new versions of MS edge (>79, January 2020)
