### ISSUE TITLE
Går ikke å invitere grupper til møter 

### ISSUE THREAD

**Issue by asnestige** [webkom/lego#1765]
![Skjermbilde 2020-01-08 kl  15 44 52](https://user-images.githubusercontent.com/38908579/71987224-17f46b00-322e-11ea-9f70-6bfe0b541008.png)

**Comment by odinuge** [comment]
![Screenshot_20200108-165325](https://user-images.githubusercontent.com/1467188/71993450-69552800-3237-11ea-9fa3-99c58a9c6d1f.jpg)

😥😥

**Comment by LudvigHz** [comment]
Closing this since the server issues have been resolved.
