### ISSUE TITLE
Photo Consent Improvements

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego#1776]
## Problem

So, as per mail from **Oline Zachariassen** there are some problems with the way `photo_consent` works. The problem is that some attendees might have an empty `photo_consent` for various reasons. We think this is due to either of the following UserFaults:

1. The Attendee writes their name on Abacard and then proceeded to enter the event without answering [**Yes**] or [**No**] to the prompt regarding photos
2. Someone has manually pressed [**Til stede**] from the main attendees' page

![image](https://user-images.githubusercontent.com/23152018/74110650-98402000-4b8e-11ea-9742-51bc758782ef.png)

Both of these sequences of events will result in `photo_consent` not being set for that registration.

## Proposed Solution

As @LudvigHz said in his mail to **Oline**, an initial solution would be to allow event administrators to modify the **consent** after the initial prompt given by Abacard. This would solve two things, firstly, that one can move people from **[Unknown]** to **[Consent]**, if they forget to answer the first time. This also solves _(in my opinion)_, the problem where people change their minds about giving consent to photographs. According some GDPR rules, one must be able to withdraw one's concent, if they want to be deleted. We already state that:

1. You can change your mind later (when you are prompted [**Yes**] or [**No**] on Abacard)
2. While hovering the concent after that, that you can send an mail to be deleted.

So with the prosed change _(see image under)_ the user would land have 3 possibilities when entering an event:

![image](https://user-images.githubusercontent.com/23152018/74110438-f23fe600-4b8c-11ea-81cc-bf9ab1dc1c92.png)

1. They answer **Yes** (good), they get `PHOTO_CONSENT`
2. They answer **No** (sucks, but fine), they get `PHOTO_NOT_CONSENT`
3. They somehow forget to answer in the midst of all chaos, they get `PHOTO_UNKNOWN`

For 1 and 2, nothing needs to be done and they can be changed later if the user changes his/her mind. For number 3, the host of the event needs to either; hunt down the ones that land on `UNKNOWN`, or send them an email the day after, and ask if they consent to the images that were taken during the event.

### Withdraw consent [workflow]

If a user changes their mind 2 weeks after the event they need to send an email to abakus@abakus.no, which PR will answer. PR can they go back to the event -> change their photo consent status, and proceed to delete all photos of the user

**Comment by erlingfn** [comment]
Looks good! I believe this will be useful to a lot of event hosts

**Comment by SmithPeder** [comment]
I'll close this due to the new proposal that's being worked on
