### ISSUE TITLE
Sort buttons are disabled and unaligned

### ISSUE THREAD

**Issue by estensen** [webkom/lego#1813]
On the Joblisting page the sort buttons are disabled and unaligned. Refreshing does not solve this. Hard refreshing does. Refreshing again brings back the problem.

<img width="240" alt="Screenshot 2020-03-17 at 19 55 04" src="https://user-images.githubusercontent.com/9142800/76891781-d9aca500-6889-11ea-9b78-383e83bf80c8.png">

**Comment by SmithPeder** [comment]
This is the same issue as https://github.com/webkom/lego/issues/1483 😢Much of `lego-webapp` is created without checking firefox at every step. I'll close this, but keep the other open 😢
