### ISSUE TITLE
Add support for exporting event registrations

### ISSUE THREAD

**Issue by odinuge** [webkom/lego#1918]
Almost all events will now require manual lists, and we SHOULD support exporting in gui so we don't have to `curl` each time.

Also, it should contain a notice about the fact that info MUST be deleted afterwords and that it should only be distributed via official abakus-channels, aka. ONLY `@abakus.no` mail and NOT slack. For external events it could be shared with the organizer, but then the event has to state that fact in the event description (or we can make support for "external" event that tells the user what info will be shared, and with whom).

Should be possible for the user to say what fields are required. Eg. not all events are interested in allergies etc.

**Comment by LudvigHz** [comment]
As an addition to this, it should be possible to do this also for open events. I.e. It should be able to use abacard for events without pools so that we can get a list of people who attended.

We could just have an event where anyone can register but I feel like this would increase friction for the user. 

This is up for discussion though.

**Comment by odinuge** [comment]
> As an addition to this, it should be possible to do this also for open events. I.e. It should be able to use abacard for events without pools so that we can get a list of people who attended.

Yeah, agree! :+1: Would probably have to create a pool with unlimited quantity (to make it work without that much change) and a custom event attr that says something like "open for all, registration upon arrival". Some simple gui work and a hook in the abacard endpoint should be pretty doable and create a lot of value for users!

If we add a `https://abakus.no/qr` with a qr-code for the logged in user, that works with abacard as well, would be awesome!

**Comment by odinuge** [comment]
Especially useful for events like diskusjonskveld and genfors!

**Comment by LudvigHz** [comment]
The abacard case is moved to a separate issue: #1927

**Comment by erlingfn** [comment]
Status on this issue:
- [ ] Create flag on the event indicating that users consent to sharing name and email for public health  concerns
- [ ] Display message on event if flag is enabled
- [ ] Write frontend logic for exporting name and email to csv

**Comment by LudvigHz** [comment]
Closed by #1980 and https://github.com/webkom/lego-webapp/pull/2001
