### ISSUE TITLE
Error with backend regex for fileupload

### ISSUE THREAD

**Issue by magnhan** [webkom/lego#1920]
So there are still some errors with the backend-regex.
It's either:
- Numbers
- Spaces
- Punctuation

**Comment by SmithPeder** [comment]
What are the filenames?

**Comment by magnhan** [comment]
"17. mai kvadrat.jpg" and "17. mai kvadrat.png"

**Comment by SmithPeder** [comment]
Can you rename them to something like `asdfasdf.jpg` and try again 👍 
There are some problems with the `regex`, either on numbers, spaces, punctuation or something else 🙃

**Comment by magnhan** [comment]
That worked!
