### ISSUE TITLE
Not allowed to react on quotes

### ISSUE THREAD

**Issue by asmundh** [webkom/lego#1971]
I'm not allowed to react using a reaction that someone else has already reacted with. See image below, where I am not allowed to react with the clown emoji. The HTTP request status is 403 Forbidden, response payload is `{"detail":"You do not have permission to perform this action."}`

![image](https://user-images.githubusercontent.com/33457035/95334091-f0f6c280-08ad-11eb-827d-432dc1b9083e.png)

**Comment by erlingfn** [comment]
Hi, this was due to a slight oversight on our part where normal users did not have permission to view single quotes, just the list. I have added this permission, so you should be able to react now. Thank you for notifying us about this bug.
