### ISSUE TITLE
Links in article are not displayed as clickable

### ISSUE THREAD

**Issue by estensen** [webkom/lego#2005]
Links don't change the mouse pointer when you hover over them. If it's not a conscious choice I would consider changing from text cursor to mouse pointer (hand) to make it more visible that the content is clickable. This also applies to the `+ :)` emoji button.

![Screen Recording 2020-11-12 at 21 20 30](https://user-images.githubusercontent.com/9142800/98992269-4cf7db00-252d-11eb-96c1-cf5b90ca778a.gif)

**Comment by LudvigHz** [comment]
Hi!
Thanks for opening the issue. The links should be fixed by https://github.com/webkom/lego-editor/pull/242. So it should be resolved as soon as we release a new version 😉. (We are waiting on https://github.com/webkom/lego-editor/pull/255)

We were not aware of the emoji issue though!
