### ISSUE TITLE
Checkboxes for filtering events do not toggle when clicking on the label

### ISSUE THREAD

**Issue by LudvigHz** [webkom/lego#2006]
This means that you cannot click on the label to toggle the checkbox. Clicking on the text should toggle the checkbox.

![events-label-bug](https://user-images.githubusercontent.com/42850232/99101471-92bbae80-25d4-11eb-94ad-832b457f1ba2.gif)

**Comment by AdrianAndersen** [comment]
This issue is present multiple places in lego-webapp. Might be an idea to create a standard component for places where we need checkboxes / radiobuttons

**Comment by LudvigHz** [comment]
> This issue is present multiple places in lego-webapp. Might be an idea to create a standard component for places where we need checkboxes / radiobuttons

There are standard components. People just don't use them correctly 🙃
