### ISSUE TITLE
Create Ability to Only Show Events  to Certain Groups (Event object permissions)

### ISSUE THREAD

**Issue by AdrianAndersen** [webkom/lego#2042]
## Problem Statement
Today, we only have the ability to select `Kun for Abakom`, but it should be possible specify which groups can see the event. (default to all users)
![image](https://user-images.githubusercontent.com/26925695/106650778-989dac00-6593-11eb-8ad7-886e18243794.png)

**Comment by iselinee** [comment]
Might be ideal to use a multiselect dropdown of groups, so that more than one can be selected.
![image](https://user-images.githubusercontent.com/43182013/108108334-c9e8a280-7090-11eb-981a-476d0b67685e.png)

**Comment by iselinee** [comment]
This way, you can choose if it should only show for specific groups
![image](https://user-images.githubusercontent.com/43182013/108120686-f527bd80-70a1-11eb-9a1b-1607f4cef3ac.png)
