### ISSUE TITLE
Next picture buttons do not work

### ISSUE THREAD

**Issue by erlingfn** [webkom/lego#2124]
![image](https://user-images.githubusercontent.com/7977650/112545262-4e2cf480-8db8-11eb-9b79-fcd719a1fba7.png)
The buttons at the bottom of the inluded image does not work as expected. When clicked a "Buffer is not defined"-error is emitted in the console

**Comment by SmithPeder** [comment]
hmm. This is because Webpack 5 doesn't polyfill for core node modules anymore, but we have the correct resolve -> fallback for `buffer` and `utils`. So it's a bit strange.
https://github.com/webkom/lego-webapp/blob/a4d5a3f61f0e5e2ad4cf8afcf74c16f78c2bfdb3/config/webpack.client.js#L129
