### ISSUE TITLE
Large article boxes looks weird on front page

### ISSUE THREAD

**Issue by amalieeh** [webkom/lego#2323]
That box for the description of "Artikler" has a lot of empty space.

![image](https://user-images.githubusercontent.com/31897129/133780316-94de193e-d402-4e80-8fe3-10ec289f62f4.png)

**Comment by amalieeh** [comment]
However, a new front page is going to be released soon, so maybe this is not critical. 😄

**Comment by SmithPeder** [comment]
😢  Yeah. We really wanted them to actually write a "better" description here. The new frontpage should take into account that people don't generally write more than 1 sentence here.

**Comment by amalieeh** [comment]
Oh, so it's a feature, not a bug?:)) 
A user mistake 🏴󠁧󠁢󠁥󠁮󠁧󠁿
