### ISSUE TITLE
Hide Gray  Badges For Interest Groups

### ISSUE THREAD

**Issue by AdrianAndersen** [webkom/lego#2333]
When you leave a group, you get a gray badge to show that you are a former member. This is great for committee memberships and HS. 
However, this does not make a lot of sense for interest groups. (Since people commonly are a member/former member of many of them at the same time) Therefore, they should be hidden from the profile page:

![Screenshot from 2021-09-23 18-33-45](https://user-images.githubusercontent.com/26925695/134547733-68d8cfc8-0ab4-4259-83bd-06468d427916.png)

**Comment by ivarn01** [comment]
I rather disagree. Being part of an interest group should, in theory, be just as great as being in a committee, HS or itDAGENE.

However, I'm not a big fan of the grey badge when the user was only part of the group for a short period of time, e.g. 2 weeks, and the timeline on hover says (yyyy - yyyy). Perhaps the badge should only be hidden when this is the case, as you could argue that the user was never really part of the group at all?

**Comment by AdrianAndersen** [comment]
Yeah, I agree that they should be equal in "value", but the thing is that you do not know whether the person has interacted with the interest group, even though they are a member. 
With itDagene, HS, committees, eg., you know that they have had X responsibilities and workloads. This is not true for interest groups.

In an ideal world, if the user has not attended any events or engaged with the interest group, they (IMO) should not get a badge stating that they were a member. However, this is not easy to monitor before we get the interest group events.

For now, I agree that a viable solution is to hide memberships shorter than 2 weeks.

**Comment by LudvigHz** [comment]
Big proposition: We show the badge by default, but let the user choose to hide it if they want to?
