### ISSUE TITLE
Cannot use contact form unless loggedIn

### ISSUE THREAD

**Issue by SmithPeder** [webkom/lego#2345]
There is code to handle anonymous users for this route,
https://github.com/webkom/lego-webapp/blob/df4b17b4e81ec652ba3296f2da26f7e4bc9a8e9e/app/routes/contact/components/ContactForm.js#L44

, but since this field needs to fetch the groups (to select recipient)
https://github.com/webkom/lego-webapp/blob/df4b17b4e81ec652ba3296f2da26f7e4bc9a8e9e/app/routes/contact/components/ContactForm.js#L69-L77

, this whole route will fail when not logged in.
![Screenshot 2021-10-09 at 15 21 43](https://user-images.githubusercontent.com/23152018/136659472-380beda1-e93b-499a-8d43-a15dc442f547.png)

**Comment by ivarnakken** [comment]
Resolved by https://github.com/webkom/lego-webapp/pull/4131
