### ISSUE TITLE
Link from joblistings opens in the same tab

### ISSUE THREAD

**Issue by juniwbjerde** [webkom/lego#2349]
The link "SØK HER" in the sidebar on the site for a job listing does not open the page the link links to in a new tab, but opens it in the same tab that abakus.no was in. This is extremely annoying, and needs to be fixed.

![image](https://user-images.githubusercontent.com/69513864/136998368-089fb478-4a59-46b2-b758-04a4b3e71ea1.png)

**Comment by ivarnakken** [comment]
Resolved by [#2270 in webapp](https://github.com/webkom/lego-webapp/pull/2270)
