### ISSUE TITLE
Remove Slate-editor specific cypress commands

### ISSUE THREAD

**Issue by eikhr** [webkom/lego#2353]
Some Cypress tests use the commands `editorType` and `editorFocus` instead of the standard `type` and `focus` commands when interacting with [Slate](https://github.com/ianstormtaylor/slate) rich-text editors. This was most likely done as a workaround because old versions of cypress did not dispatch the correct events that the Slate-editor is listening for. This has been fixed in newer Cypress versions, so `editorType` and `editorFocus` can be removed and replaced with the standard `type` and `focus` commands.

**Comment by EikHR** [comment]
Actually a lot of the editorFocus()-calls can probably be removed completely, as the editor already gets focused by being clicked

**Comment by LudvigHz** [comment]
Have you tested with different browsers as well? As you might have seen this is an ugly workaround, and there is a complete editor test that runs only on Firefox, as that's the only browser where the test works. It's awesome if we can reenable that test on chrome/elector as well :raised_hands:.
