### ISSUE TITLE
Enhance UX of mazemap tool

### ISSUE THREAD

**Issue by PeterJFB** [webkom/lego#2531]
The mazemap tool could use a few adjustments to increase the user experience on mobile and desktop<3. Some of the notes are:
- Scrolling on desktop will be blocked when cursor moves above the map (most noticeable when the web-page is on half of the screen)
- Scrolling on mobile becomes tedious, as the map covers the entire width and half the page on many devices (see image below).

![image](https://user-images.githubusercontent.com/42469466/155180973-4de2b720-c42d-458e-b312-0f3a76ca3a0a.png)

There are many options to fix this: Increase the margin on mobile, move the map into a dropdown etc. One could also look into what features the module has to mitigate this (e.g. requiring to use two fingers to move the map).

It would also be nice to group the mazemap-checkbox with it's search field, as not to be confused by its function:
![image](https://user-images.githubusercontent.com/42469466/155181553-47800987-0307-433a-88c3-b5276c56914d.png)

**Comment by ollfkaih** [comment]
As for unwanted interactivity of the map, I'd suggest setting `scrollZoom` to false in the `Map` constructor, and then you can do something like 
```
embeddedMazemap.on('click', () => {  
      embeddedMazemap.scrollZoom.enable();
      embeddedMazemap.touchZoomRotate.enable();
})
```
You can use [`mouseout`](https://docs.mapbox.com/mapbox.js/api/v3.3.1/l-map-class/#map-events) to detect the mouse being moved out of the map, but considering mobile, I'd suggest having a button on the map to toggle interactivity using the above methods.
