### ISSUE TITLE
Remove excess quote when loading the list of abaqutes

### ISSUE THREAD

**Issue by ulrik2204** [webkom/lego#2587]
When entering the frontpage, and clicking on "Overhørt" to see the list of quotes, the shown quote at the frontpage (even if it is very old) is always at the end of the currently shown list (before "Last in flere" is clicked). This issue suggests to remove the shown quote from the redux state when entering the overview quote page, so that it can be retrieved from the backend when applicable instead.

**Comment by eikhr** [comment]
fixed in webkom/lego-webapp#2669
