### ISSUE TITLE
Most of webapp re-renders every time a fetch success action is dispatched

### ISSUE THREAD

**Issue by eikhr** [webkom/lego#2752]
It seems like all objects in entityReducers (state.x.byId[x]) are "changed" every time a fetch success action is dispatched even if it is completely unrelated. Meaning that a strict equality (===) between the object in oldState and newState returns false even though a deepEqual would return true. Redux uses strict equality (ish) to compare the objects from state, so it causes a lot of components to re-render unneccesarily. Notably this includes the `App`-component and a bunch of it's children because `currentUser` has "changed". 

Seems like it's caused by [this](https://github.com/webkom/lego-webapp/blob/e242f70f26db666e664cf511757df63ab95d7181/app/utils/createEntityReducer.js#L126) (and possibly other) uses of merge, that clones all the objects (breaking strict equality) even if nothing has changed. If nothing changes they should instead be directly copied over (by reference) to the new state)

Not a huge issue, but would probably improve performance a bit if someone fixed it.

**Comment by LudvigHz** [comment]
Nice catch! This can definitely benefit from being fixed/improved :raised_hands:.

Solving this is actually relatively easy: Just use [`immer`](https://immerjs.github.io/immer/) in `createEntityReducer` to do the state mutation (as we do in other reducers) and it should take care of the problem for us.

**Comment by eikhr** [comment]
Completed in https://github.com/webkom/lego-webapp/pull/3772
