### ISSUE TITLE
Title in tab is bugged when creating a new survey

### ISSUE THREAD

**Issue by ingraso** [webkom/lego#2867]
When creating a new (or editing a) survey the text "[Object object] | Abakus.no" is present in the title of the tab. When creating a new meeting for example, the title of the tab is "Nytt møte | Abakus.no", so something on the same format would be preferable.

![image](https://user-images.githubusercontent.com/43182025/186270615-6e188749-30bd-4b63-ba0b-51b01f16f393.png)

**Comment by haukkagu** [comment]
Closed by webkom/lego-webapp#3120
