### ISSUE TITLE
Improve styling of interest group leader

### ISSUE THREAD

**Issue by eikhr** [webkom/lego#2880]
![Screenshot 2022-08-25 at 14 29 48](https://user-images.githubusercontent.com/8343002/186664974-58c16732-9baf-4a91-bc55-7f79ba0fecf3.png)
The star is nice, but it is large and not aligned with the picture.

**Comment by JosephBusayo** [comment]
Reduce size of star by setting thw width property to a smaller px or preferably rem in the CSS.
star{ width : 12rem;}.
Also there's an error in the spelling of Leader
