### ISSUE TITLE
Search icon disappears on attendees list 

### ISSUE THREAD

**Issue by Arashfa0301** [webkom/lego#2893]
On the attendees list for any event, the search icon for users disappears after the first use and only shows up after refreshing. Upon further inspection it looks like that the component loses its visibility for some reason. 

Update: Looks like this issue applies to all of the pages with the same search icon component. For example emails.

Before use:
![Screenshot 2022-08-29 at 16 39 28](https://user-images.githubusercontent.com/90712892/187227535-adddb8b0-0c59-4e3d-b42e-6fe1ff65beff.png)

After use:
![Screenshot 2022-08-29 at 16 39 44](https://user-images.githubusercontent.com/90712892/187229959-9dc76cb1-a8b5-45b0-ae20-6948edabe7eb.png)

**Comment by Arashfa0301** [comment]
The problem lies here (Table/index.js)  if anyone is interested in fixing it:
![image](https://user-images.githubusercontent.com/90712892/196176741-706ee146-5155-4903-bae8-d33863ceac47.png)

**Comment by LudvigHz** [comment]
Fixed in https://github.com/webkom/lego-webapp/pull/3142
