### ISSUE TITLE
Shareable link for surveys does not work

### ISSUE THREAD

**Issue by eikhr** [webkom/lego#2931]
It seems to give a 500 error when trying to access the survey via the link. 

Accessing the link causes these two Sentry issues: https://sentry.io/organizations/abakus/issues/3508647663 and https://sentry.io/organizations/abakus/issues/2301511476

**Comment by norbye** [comment]
Is this still unresolved?
And what is the shareable link that you try to access? Directly accessing `https://abakus.no/surveys/<id>` and `https://abakus.no/surveys/<id>/answer` seems to work fine on my end.

**Comment by LudvigHz** [comment]
This was fixed in #3020 (and is also marked as resolved in Sentry)
