### ISSUE TITLE
Improve the layout and design of sidebar

### ISSUE THREAD

**Issue by mattiastofte** [webkom/lego#2933]
There are quite a handful of problem with the current sidebar. Margins are bugged and visibility is not optimal. I also think the arrows are a bit loud design wise.

What to improve:
- Margins, paddings & layout
- Divider
- Arrow icons
- Auto expansion of the category that you are under

**Comment by ivarnakken** [comment]
Resolved in https://github.com/webkom/lego-webapp/pull/3553, https://github.com/webkom/lego-webapp/pull/3567 and https://github.com/webkom/lego-webapp/pull/3593
