### ISSUE TITLE
Tooltip doesn't overlay other elements

### ISSUE THREAD

**Issue by olestole** [webkom/lego#2941]
I created a fix and was to create a PR, but `ERROR: Permission to webkom/lego-webapp.git denied to olestole.` 🤷‍♂️ 

<img width="369" alt="image" src="https://user-images.githubusercontent.com/27623888/190771723-77dc9186-36c5-477d-8474-1ce8f489d96a.png">

**Comment by eikhr** [comment]
It's great that you have created a fix, we would love the PR. You just need to fork the repo, push the fix to the fork, and when creating a PR in the forked repo you can select to merge into the main repo:)
