### ISSUE TITLE
fix formatting for event participants information

### ISSUE THREAD

**Issue by Arashfa0301** [webkom/lego#2944]
There seems to be a problem with formatting as the screenshot shows below. This is on a 13-inch Macbook. Looks fine on mobile.

<img width="324" alt="Screenshot 2022-09-19 at 12 41 14" src="https://user-images.githubusercontent.com/90712892/191000569-b3fd4657-e73d-46db-8193-6595e53c686e.png">

**Comment by danielyanghansen** [comment]
I'm assuming this is on mobile? Might be iPhone specific, but it's always nice to increase device compatability

**Comment by Arashfa0301** [comment]
I edited the comment. It is on a 13-inch Mac.

**Comment by ivarnakken** [comment]
This has been fixed
