### ISSUE TITLE
fix styling for events filtering options

### ISSUE THREAD

**Issue by Arashfa0301** [webkom/lego#2946]
The styling for the components in the screenshot below could be better in my option. the check boxes could be aligned with the text and the menu could for example not be attached to the line below it.

<img width="627" alt="image" src="https://user-images.githubusercontent.com/90712892/191006697-630f4191-c567-4456-aae0-4ad197d1ae40.png">

**Comment by itsisak** [comment]
closed by https://github.com/webkom/lego-webapp/pull/3118

**Comment by itsisak** [comment]
closed by https://github.com/webkom/lego-webapp/pull/3118
