### ISSUE TITLE
Misalignment of the notification dropdown

### ISSUE THREAD

**Issue by falbru** [webkom/lego#2950]
If you open the notification dropdown for the first time, the dropdown will be aligned properly like shown on the picture below.

![aligned1](https://user-images.githubusercontent.com/66320400/191366819-bbf83967-956e-43e4-9035-a23a6f03edbd.png)

However, if you close it and then open it again, it will be misaligned:

![aligned2](https://user-images.githubusercontent.com/66320400/191366843-f667dda2-843a-4a5e-8842-4c18fe267e7f.png)

What's extra weird about this bug is that it only occurs on the front page. On every other page I've tested (like "Arrangementer" and "Karriere"), the dropdown is always aligned properly.

**Comment by ivarnakken** [comment]
I'm having a hard time reproducing this deterministically, but I believe I've experienced this before and it's indeed a weird bug. Should be fixed https://github.com/webkom/lego-webapp/pull/2381 though, whenever that happens ...

**Comment by ivarnakken** [comment]
@haukkagu, do you manage to reproduce the bug with the slightly new dropdown?

**Comment by haukkagu** [comment]
@ivarnakken Unfortunately, yes.
![image](https://user-images.githubusercontent.com/66320400/218594306-55ab4ee0-7e91-4f34-950c-6469277dcbfe.png)
