### ISSUE TITLE
Payment counter should show everyone who has payed

### ISSUE THREAD

**Issue by LudvigHz** [webkom/lego#2995]
Right now, the payment counter in the attendees page shows how many of those who are registered that have payed.
However, it is necessary for the event admins to know how many has payed in _total_, which includes those who have payed but unregistered.

We can either add another number showing the total payed amount, just how many of those unregistered has payed, or something else smart.

**Comment by jonasdeluna** [comment]
https://github.com/webkom/lego-webapp/pull/3532
