### ISSUE TITLE
Migrate from CAPTCHA to Turnstile

### ISSUE THREAD

**Issue by ollfkaih** [webkom/lego#3005]
Turnstile
* is not from *Google*.
* doesn't force users to help train Google's car AI.
* easy (?) to [migrate to](https://developers.cloudflare.com/turnstile/get-started/migrating-from-recaptcha/).
* solves the stupid issue with showing captchas so early they expire (Bc. a Turnstile token is valid for 300 seconds).

Closes #2291

**Comment by LudvigHz** [comment]
Another alternative is also to use hCaptcha, which is very widely used and tested. https://www.hcaptcha.com/

It _does_ help train AIs as well, just not for a single entity, but anyone can use the results.

_And you donate to charity by using it_

**Comment by ollfkaih** [comment]
HCaptcha is fine, but it has the same horrible ux when it thinks you're a bot or adblocker trips it up.
