### ISSUE TITLE
Support the display of roles in groups and committees

### ISSUE THREAD

**Issue by ingraso** [webkom/lego#3050]
At the moment, we only display the leader and co-leader roles on the flatpages of each group or committee. It would be preferable to display the specific roles of the committee and group members to make it easier to get in touch with the correct people. We have support for having different roles in groups, so it would be nice to display this on the flatpages.

This would also be very nice with the recent addition of the revue groups on the flatpages, as some of the revue groups use other names than "leader" for their leaders, such as "director".

As an example, readme could have the following members with the following roles:
![image](https://user-images.githubusercontent.com/43182025/199589868-b484a5e4-9f6a-4048-a825-2d5cfb28ae12.png)

But in the overview, only the role of the leader is shown, and not the role "Økonomiansvarlig".
![image](https://user-images.githubusercontent.com/43182025/199590602-4c55bb0f-8710-4074-9195-f6f9fb637a9a.png)

**Comment by ivarnakken** [comment]
Much needed! This was sort of started with [this](https://github.com/webkom/lego-webapp/pull/3321), but I believe it should be iterated on to be more abstract and support more roles. @Arashfa0301, would you like to take on the task?
