### ISSUE TITLE
Waitinglist sorting is incorrect when you are admitted to an event

### ISSUE THREAD

**Issue by LudvigHz** [webkom/lego#3211]
The core issue is that the `Din plass i venteliste: x` shows an incorrect position. 

After investigation, we see that the data for events, either from the selector/reducer in the frontend or the serializer in the backend, is different based on whether you are registered to the event or not.

If you are _not_ registered, you can inspect the `waitingRegistrations` on the `EventDetailRoute.ts` and see that the list is sorted correctly according to registration date. However, when you register, the registration objects are sorted differently and incorrectly.

This needs a bit more investigation to see where the problem originates, but I suspect that it is in https://github.com/webkom/lego in the serializer that probably is different based on whether you are registered or not.

**Comment by ivarnakken** [comment]
Resolved by #3227
