### ISSUE TITLE
Hovering icons should not display the icon's name

### ISSUE THREAD

**Issue by ingraso** [webkom/lego#3217]
This applies to a lot of our icons, and is a bit weird behavior. Either the text could be changed to something more informative, depending on the usage of the icon, or it could be hidden.

**Examples**
![Screenshot from 2023-02-10 17-39-55](https://user-images.githubusercontent.com/43182025/218146733-dc78b637-b123-4e7b-81cb-cdc584c485e5.png)
![Screenshot from 2023-02-10 17-42-14](https://user-images.githubusercontent.com/43182025/218147299-b506f8a8-c634-4dca-a8a2-585ac62f6902.png)
![Screenshot from 2023-02-10 17-42-27](https://user-images.githubusercontent.com/43182025/218147351-42804bf1-9e9a-4241-9b90-5e3fa63d2f07.png)

**Comment by ollfkaih** [comment]
The most recent ionicons makes this difficult I believe

**Comment by ivarnakken** [comment]
This is actually impossible with the current ionicons, so I'll close this for now.
