### ISSUE TITLE
Wrong warning appears: "Cannot register to event because of unanswered survey" shows up for events where already registered 

### ISSUE THREAD

**Issue by danielyanghansen** [webkom/lego#3324]
The warning appears even though it is not supposed to.
How to recreate:
 - Register for a future event
 - Receive a survey
 - Look at page for said future event 

![image](https://user-images.githubusercontent.com/55885035/233385770-74e14021-1e7a-42a9-be8b-30f3dd0e3c75.png)

**Comment by ivarnakken** [comment]
This is fixed
