### ISSUE TITLE
Add separator to organizing committee 

### ISSUE THREAD

**Issue by jonasdeluna** [webkom/lego#3498]
![Screenshot_2023-09-29-15-17-44-37_3aea4af51f236e4932235fdada7d1643](https://github.com/webkom/lego/assets/113468143/7f284d0d-fed7-4a4e-bc68-5b0a7f2f19c4)

Add separator between committee name and email

**Comment by rahultg1411** [comment]
Hey, I am Rahul. I would like to solve this issue. Could you please assign this to me?

**Comment by ivarnakken** [comment]
Email is now in a tooltip
