### ISSUE TITLE
Modal for admin unregister does not automatically close

### ISSUE THREAD

**Issue by danielyanghansen** [webkom/lego#3503]
### Steps to reproduce:

- 1: Be admin / author for an event (so you have the rights to admin unregister)
- 2: Have someone be registered to that event
- 3: Go to the registration tab under the event admin page and click unregister (far right)
![image](https://github.com/webkom/lego/assets/55885035/eb1a1676-28a2-4322-9f8b-e8be23ece2aa)
- 4: Click "Ja" under "Bekreft utmelding"
![image](https://github.com/webkom/lego/assets/55885035/3f699494-8d03-45a4-82d4-0d7e7ef1f9e1)

**Comment by SaiNikhil02** [comment]
@danielyanghansen can you please assign me this issue
