### ISSUE TITLE
Shrink click area for "Bruk mazemap" checkbox

### ISSUE THREAD

**Issue by ianmaks** [webkom/lego#3567]
Shrink click area for "Bruk mazemap"-checkbox when creating meetings.

When selecting beginning and end times for meetings, clicking outside the datetime-selector to close it will also click the mazemap-checkbox, for which the click area spans the entire width of the page.

![Screenshot 2024-03-09 at 17 54 29](https://github.com/webkom/lego/assets/40581767/03b11e97-ab0b-4241-8db7-83f03c6810e7)

For a slight improvement in quality of life, the click area can be made to only cover the checkbox and descriptive text for "Bruk mazemap".

**Comment by norbye** [comment]
Thank you for reporting the issue! It is now fixed, and deployed to abakus.no:)

**Comment by ianmaks** [comment]
Thank you for fixing my issue, although I actually would have wanted to fix it myself 😩. Can you find me a replacement?

**Comment by norbye** [comment]
Whops - sorry about that..

I don't think the two first have been added as issues on github yet, but they shouldn't™️  be too hard to fix;

* [frontend] On abakus.no/events the "Last inn mer" button is displayed even if there are no more events to be fetched
	* Ideally the button would be hidden. An example of how it can be done (except there it is not hidden) can be seen on the event-list of the frontpage
* [backend] When you reset your password, the email that is sent to you does not include your name [backend]
	* This requires you to run both the backend and the frontend locally to debug it
* [frontend] https://github.com/webkom/lego/issues/1382
	* The sorting/grouping could be done in different ways - currently it is grouped in three sections (1: leader and co-leader, 2: active members, 3: active retirees) and retirees are hidden.
	* My initial suggestion if you want to look at this one would be the following sorting/grouping
		* Group 1: leader+co-leader, sorted with leaders first then by seniority (newest first)
		* Group 2: active members, sorted by non-member roles (social, economy, etc.) first and normal members last, then by seniority (newest first)
		* Group 3: active retirees, sorted by seniority (newest first)
