### ISSUE TITLE
frontend, bug (low pri): Settings/edit profile on others visible for non-admins (changes not working)

### ISSUE THREAD

**Issue by casfaar** [webkom/lego#3647]
Settings wheel icon visible, clicking gives the edit profile view (but not displaying sensitive info, and trying to change values returns an error.
Context: Viewing a different users profile page from a non-admin user.
Head of "interessegruppe" might matter in case not reproducible for another account.

<img width="276" alt="Screenshot 2024-10-03 at 21 19 14" src="https://github.com/user-attachments/assets/3a7defea-4061-4555-b3b6-c1ec4dcc023f">

**Comment by eikhr** [comment]
Fixed in https://github.com/webkom/lego-webapp/pull/5043
