### ISSUE TITLE
Fix brand page flex direction

### ISSUE THREAD

**Issue by TobiasBorning** [webkom/lego#3674]
The content in the page at abakus.no/brand, does not have the correct flex direction.
<img width="1081" alt="image" src="https://github.com/user-attachments/assets/083b2659-1a62-4535-8255-50104c43a217">
This should be changed to flex in the column direction.
Found a fix to the issue, the creator of the page added flex direction in the styles.css file, but should have used the property on the Flex component.

**Comment by ivarnakken** [comment]
Thanks for the issue - we'll get the fix into prod asap 😄

**Comment by TobiasBorning** [comment]
I wanted to fix it! Need my lego pin:((((
