### ISSUE TITLE
Write a migration tool to export models from NERD to LEGO

### ISSUE THREAD

**Issue by kotlarz** [webkom/lego#590]
PR can be found in NERD here: https://github.com/webkom/nerd/pull/390

Models marked with :red_circle: are models that are planned for release, but not yet completed/ready.
Models marked with :white_check_mark: are ready for release data export.
Model and/or model fields marked with :sos: are models/fields that dependent on another model, and is therefore not yet completed/ready.
Model fields with a checked checkbox define the new field like so:
`old_field_name -> new_field_name`
i.e.
`lead_paragraph -> description`

### AluminiUser
- [ ] name
- [ ] surname
- [ ] birthday
- [ ] email_job
- [ ] email_private
- [ ] adress
- [ ] post_number
- [ ] post_city
- [ ] finished_studies
- [ ] mobile
- [ ] telephone

### Announcement :white_check_mark: -> (articles.Article)
- [x] author -> author
- [x] created -> created_at & updated_at
- [x] title -> title
- [ ] type
- [ ] show_start
- [ ] show_stop
- [x] lead_paragraph -> description
- [ ] compiled_lead_paragraph
- [x] text -> text
- [ ] text_richtext
- [ ] url
- [x] image -> cover
- [ ] comments

### AnnouncementType
- [ ] name
- [ ] title

### CareerPage
- [ ] title
- [ ] content
- [ ] category
- [ ] slug

### JobListing :white_check_mark: (-> joblistings.Joblisting)
- [x] author -> created_by & updated_by
- [x] created -> created_at & updated_at
- [x] company -> company
- [x] title -> title
- [ ] openings
- [x] deadline -> deadline
- [x] visible_from -> visible_from
- [x] visible_to -> visible_to
- [x] job_type -> job_type
- [x] workplaces -> workplaces
- [x] from_year -> from_year
- [x] to_year -> to_year
- [x] application_url -> application_url
- [ ] application_email
- [x] application_intro -> description
- [x] application_text -> text
- [ ] application-text_richtext
- [x] contact -> responsible
- [x] tags -> tags

### JobListingTag :white_check_mark: (-> tags.Tag)
- [x] name -> tag

### WorkPlace :white_check_mark: (-> joblistings.Workplace)
- [x] name -> town

### CompanyStatus
- [ ] text
- [ ] color

### CompanyContact :white_check_mark: (-> companies.CompanyContact)
- [x] name -> name
- [x] position -> role
- [x] mail -> mail
- [x] phone -> phone
- [x] mobile -> mobile
- [x] date_created -> created_at & updated_at
- [x] company -> company
- [x] public -> public

### CompanyRelationship :white_check_mark: (-> companies.SemesterStatus)
- [x] year -> year
- [x] semester -> semester
- [x] company -> company
- [x] status -> contacted_status
- [x] contract -> contract

### CompanyInterest
- [ ] company
- [ ] contact
- [ ] email
- [ ] semesters
- [ ] events
- [ ] advertise
- [ ] collaboration
- [ ] itdagene
- [ ] comments

### Mail
- [ ] creator
- [ ] occasion
- [ ] time
- [ ] text

### MailForm
- [ ] recipients

### EventType
- [ ] ID
- [ ] name
- [ ] color
- [ ] identifier

### Event :white_check_mark: (-> events.Event)
- [x] creator -> created_by & updated_by
- [x] created -> created_at & updated_at
- [ ] survey
- [x] name -> title
- [ ] calendar_name
- [x] type -> event_type
- [x] intro -> description
- [ ] compiled_intro
- [x] description -> text
- [ ] compiled_description
- [x] location -> location
- [x] capacity -> Pool.capacity
- [ ] is_registration_required
- [x] image -> cover
- [x] start_date -> start_time, (Pool.activation_date + 7), (Pool.unregistration_deadline - 5)
- [x] end_date -> end_time
- [x] viewable_by -> can_view_groups ('Abakom' if event.viewable_by == 2 else 'Users')
- [ ] favorites
- [ ] penalties
- [ ] grants
- [ ] comments
- [x] company -> company
- [x] penalty_weight -> penalty_weight
- [x] penalty_weight_on_not_present -> penalty_weight_on_not_present
- [x] heed_penalties -> heed_penalties
- [x] captcha -> use_captcha
- [x] feedback_when_registrating -> feedback_required
- [ ] feedback_when_registrating_text
- [ ] feedback_when_registrating_forced
- [ ] feedback_when_registrating_forced_text
- [ ] allow_multiple_ticket
- [ ] max_tickets_per_user
- [ ] only_members_can_bring_guests
- [x] pay_for_tickets -> is_priced
- [x] price_members -> price_member
- [x] price_guests -> price_guest
- [ ] send_mail_on_register
- [ ] mail_on_register
- [ ] language

### GrantPreset
- [ ] name
- [ ] role
- [ ] group
- [ ] order

### PaymentType
- [ ] ID
- [ ] name
- [ ] identifier

### Registration :white_check_mark: (-> events.Registration)
- [x] user -> user
- [x] event -> event
- [x] date -> registration_date
- [x] unregister_date -> unregistration_date
- [x] status -> status
- [x] presence -> presence
- [x] admin_reg_reason -> admin_reason
- [ ] admin_unreg_reason
- [ ] bumped_after_unreg_limit
- [ ] ticket_count
- [ ] feedback
- [ ] payment_type

### ICalUserKey
- [ ] user
- [ ] key

### Country
- [ ] name
- [ ] code
- [ ] text_visa
- [ ] text_insurance
- [ ] text_education_system
- [ ] text_special_stuff

### School
- [ ] name
- [ ] country
- [ ] abbreviation
- [ ] text_how_to_apply
- [ ] text_courses_info
- [ ] text_financial
- [ ] text_contact_info
- [ ] text_living_situation
- [ ] text_good_to_know
- [ ] text_transport
- [ ] text_activities

### Blog
- [ ] title
- [ ] url
- [ ] rss_feed
- [ ] country
- [ ] school

### Page
- [ ] title
- [ ] slug
- [ ] content

### PositionLock
- [ ] position
- [ ] instance
- [ ] active
- [ ] object_id
- [ ] content_type

### MailMapping :white_check_mark: (-> users.User, emails.EmailAddress)
- [x] address -> User.internal_mail, EmailAddress.email

### GroupMapping(MailMapping) :white_check_mark: (-> emails.EmailList)
- [x] group -> groups
- [x] role -> group_roles
- [ ] restricted
- [ ] opt_in
- [ ] opt_out
- [ ] voluntary_members
- [ ] description

### UserMapping(MailMapping) :white_check_mark: (-> users.User)
- [x] user -> User.user

### RawMapping(MailMapping)
- [ ] to_address
- [ ] desc

### RawGroupMapping(MailMapping)
- [ ] to_address
- [ ] desc
- [ ] group
- [ ] role

### RestrictedMapping
- [ ] group_mapping
- [ ] event_mapping
- [ ] token
- [ ] from_address
- [ ] timeout

### Meeting :white_check_mark: (-> meetings.Meeting)
- [x] time -> start_time
- [x] location -> location
- [x] plan -> report
- [x] title -> title
- [x] creator -> created_by, updated_by
- [x] date_last_updated -> updated_at
- [x] date_created -> created_at
- [ ] date_sent
- [x] published -> deleted
- [ ] comments

### GroupOfParticipants
- [ ] meeting
- [ ] comittee

### Participant :white_check_mark: (-> meetings.MeetingInvite)
- [x] meeting -> meeting
- [ ] group
- [x] user -> user
- [x] status -> status

### Referent :white_check_mark: (-> meetings.Meeting)
- [ ] meeting
- [x] user -> Meeting.report_author

### StaticPage :white_check_mark: (-> flatpages.Page)
- [ ] parent
- [ ] name
- [x] title -> title
- [ ] relative_index

### StaticPageRevision :white_check_mark: (-> flatpages.Page)
- [ ] page
- [ ] message
- [x] creator -> Page.created_by, Page.updated_by, Page.author
- [x] created -> Page.created_at, Page.updated_at
- [x] content -> Page.content

### StaticPageTag
- [ ] title
- [ ] slug
- [ ] pages

### WeeklyMail
- [ ] send_date
- [ ] important
- [ ] hs_message
- [ ] events
- [ ] joblistings

### MailInfoItems
- [ ] header
- [ ] information
- [ ] mail

### Poster
- [ ] title
- [ ] event
- [ ] joblisting
- [ ] info
- [ ] custom
- [ ] ordered_date
- [ ] finished_date
- [ ] finished
- [ ] deadline
- [ ] receipt
- [ ] assigned_user
- [ ] ordered_by

### VectorLogo
- [ ] file
- [ ] png
- [ ] company

### Reward
- [ ] date
- [ ] points
- [ ] description
- [ ] user
- [ ] given_by

### PortofolioCategory
- [ ] title
- [ ] slug

### PortofolioItem
- [ ] title
- [ ] file
- [ ] image
- [ ] date
- [ ] category
- [ ] made_by
- [ ] public
- [ ] rating

### ProtectedFile :white_check_mark: (-> companies.CompanyFile, files.File)
- [x] file -> CompanyFile.file, File.key
- [ ] permission
- [ ] related_object_content_type
- [ ] related_object_object_id
- [ ] related_object

### Quote :white_check_mark: (-> quotes.Quote)
- [x] submitter -> created_by, updated_by
- [x] submitted -> created_at, updated_at
- [x] title -> title
- [x] text -> text
- [x] approved -> approved
- [x] source_text -> source
- [ ] rating

### QuoteRating
- [ ] quote
- [ ] user

### Readme
- [ ] submitter
- [ ] submitted
- [ ] announcement
- [ ] name
- [ ] published
- [ ] issue
- [ ] pdf

### Survery
- [ ] creator
- [ ] created
- [ ] title
- [ ] from_date
- [ ] to_date
- [ ] event_type
- [ ] mandatory

### SurverySubmission
- [ ] survery
- [ ] user
- [ ] activeFrom
- [ ] submittedTime
- [ ] submitted

### Question
- [ ] survery
- [ ] question
- [ ] relative_index
- [ ] mandatory

### Alternative
- [ ] question
- [ ] alternative
- [ ] fieldType

### SurveryResult
- [ ] alternative
- [ ] user
- [ ] survery
- [ ] date
- [ ] answer

### TemplateType
- [ ] name
- [ ] comment
- [ ] image

### Screen
- [ ] template_type
- [ ] creator
- [ ] created
- [ ] title
- [ ] text
- [ ] image
- [ ] start_date
- [ ] end_date
- [ ] event
- [ ] event_type
- [ ] event_date
- [ ] event_location

### UserFile :white_check_mark: (-> files.File)
- [x] user -> user
- [ ] group
- [x] date -> created_at 
- [ ] name
- [x] file -> file.name -> key

### QuasselUser
- [ ] userid
- [ ] username
- [ ] password

### LevelUp
- [ ] user
- [ ] from_role
- [ ] to_role
- [ ] date

### Election
- [ ] title
- [ ] description
- [ ] public_results
- [ ] creator
- [ ] active
- [ ] mutable

### GroupOfParticipants
- [ ] meeting
- [ ] comittee

### Participant
- [ ] election
- [ ] group
- [ ] user
- [ ] not_voted
- [ ] verifies_left

### Alternative
- [ ] election
- [ ] label

### Vote
- [ ] alternative
- [ ] receipt

### Comment :white_check_mark: (-> comments.Comment)
- [x] user -> created_by, updated_at, can_edit_users
- [x] created -> created_at
- [x] edited -> updated_at
- [x] text -> text
- [x] object_id -> object_id
- [x] content_type -> content_type

### Group :white_check_mark: (-> users.AbakusGroup)
- [x] name -> name
- [x] description -> description
- [x] is_committee -> is_committee
- [ ] logo
- [ ] public

### Membership(MembershipModel) :white_check_mark: (-> users.Membership)
- [x] user -> user
- [x] group -> abakus_group
- [x] role -> role
- [ ] from_date -> start_date

### MembershipHistory(MembershipModel) :white_check_mark: (-> users.Membership)
- [x] user -> user
- [x] group -> abakus_group
- [x] role -> role
- [x] from_date -> start_date
- [x] to_date -> end_date

### Notification
- [ ] type
- [ ] created
- [ ] expires
- [ ] key
- [ ] text_kwargs
- [ ] view_kwargs
- [ ] absolute_url

### NotificationStatus
- [ ] user
- [ ] notification
- [ ] seen

### NotificationType
- [ ] name
- [ ] title
- [ ] description
- [ ] happens_when
- [ ] view
- [ ] link_goto
- [ ] link_ignore
- [ ] default_site
- [ ] default_mail
- [ ] auto_remove

### NotificationSetting
- [ ] user
- [ ] type
- [ ] site
- [ ] mail

### PendingUser
- [ ] username
- [ ] key

### Role :white_check_mark: (-> users.AbakusGroup, users.Membership.role)
- [x] name -> name, AbakusGroup.name + ' ' + role
- [ ] short_name
- [x] description -> AbakusGroup.description
- [ ] logo
- [ ] public

### User :white_check_mark: (-> users.User)
- [x] username -> username
- [x] name -> first_name
- [x] surname -> last_name
- [x] mail -> email, student_username `if '@stud.ntnu.no' in email`
- [ ] image
- [ ] password
- [ ] new_password
- [ ] new_password_valid_until
- [ ] ldap_hash
- [ ] rfid_card_number
- [ ] twitter
- [ ] facebook
- [ ] linkedin
- [ ] protected_storage
- [ ] cv

### CompanyUser(User) :white_check_mark: (-> companies.Company)
- [ ] intro
- [x] description -> description
- [ ] description_richtext
- [x] phone -> phone
- [ ] fax
- [x] url -> website
- [x] postal_address -> address
- [ ] billing_address
- [x] student_contact -> student_contact
- [ ] phone_appointment
- [x] published -> active
- [ ] main_partner
- [ ] comments

### PermissionGrant
- [ ] action
- [ ] user
- [ ] group
- [ ] role
- [ ] refers_deleted
- [ ] from_date
- [ ] to_date
- [ ] object_id
- [ ] content_type

### StudentUser(User)
- [ ] first_login
- [ ] phone

### UserPenalty :white_check_mark: (-> users.Penalty)
- [x] user -> user
- [x] created -> created_at, updated_at
- [x] reason -> reason
- [x] weight -> weight
- [ ] object
- [x] object_id -> source_event
- [ ] content_type

### UserSettings :rescue_worker_helmet: 
- [ ] user
- [ ] mail_user_disable
- [ ] mail_bounce_disable
- [ ] mail_bounces
- [ ] accepted_terms
- [ ] email_visible_in_profile
- [ ] phone_visible_in_profile
- [ ] visible_in_event_list
- [ ] language

**Comment by eirsyl** [comment]
Useful?
