### ISSUE TITLE
Switch from ES _suggest to _search

### ISSUE THREAD

**Issue by orhanhenrik** [webkom/lego#601]
`/_suggest` endpoint is deprecated
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-suggesters.html
> _suggest endpoint has been deprecated in favour of using suggest via _search endpoint. In 5.0, the _search endpoint has been optimized for suggest only search requests.

**Comment by eirsyl** [comment]
Fixed when upgrading to ES 6
