### ISSUE TITLE
Sort event registrations by relevance 

### ISSUE THREAD

**Issue by finnss** [webkom/lego#889]
Ideally you should care about the people in this box:

<img width="327" alt="skjermbilde 2017-10-24 kl 16 46 05" src="https://user-images.githubusercontent.com/14221386/31949963-dae6420c-b8da-11e7-9059-77d7e747fbe2.png">

The front-end just displays the first 10 registrations, so we could sort them by relevance back-end to make this view interesting to users. How exactly to determine relevance is more finicky, but a good start would sorting by how many groups you have in common with each user. We could also attempt weighing different groups differently – people might be likely to care more about Abakom groups than interest groups, for instance.

This is certainly a nice-to-have feature, no immediate rush.

**Comment by hanswilw** [comment]
#1086 adds support for this. It finds the intersection of the request user and each registrated user's abakus_group memberships, counts them and ordering them by this number. We can roll with this for now, and re-evaluate it at a later point when we consider followers (#71).
