### ISSUE TITLE
Sync to LDAP removes Abakus leader from the abakus_leader-group on confluence

### ISSUE THREAD

**Issue by edvardvb** [webkom/lego#923]

**Comment by odinuge** [comment]
What is the status on this @edvardvb? Does it work, or do we need to fix some stuff?

**Comment by edvardvb** [comment]
Seems good, not sure why it works now 🤔

**Comment by SmithPeder** [comment]
![soundsgood](https://user-images.githubusercontent.com/23152018/46405534-d27eef00-c708-11e8-9549-f0db9c7376e8.jpg)

**Comment by odinuge** [comment]
:upside_down_face: :iphone:
