### ISSUE TITLE
Verifying student mail puts you in first grade 

### ISSUE THREAD

**Issue by martinhath** [webkom/lego#963]
Probably due to [this](https://github.com/webkom/lego/blob/master/lego/apps/users/views/student_confirmation.py#L99).
This is an issue, since there are users without verified student mails who aren't new or in first grade. 

Fix: check if the user is in a class group already. If they are, do nothing.

[User in multiple groups](https://abakus.no/users/nicolafr)

We should probably also check for other users who are in multiple groups.

**Comment by kotlarz** [comment]
Fixed in #1272
