### ISSUE TITLE
Remove (or change) author field from Article

### ISSUE THREAD

**Issue by ekmartin** [webkom/lego#978]
I don't think we really need this. I think the original idea was that it should be possible to have someone post an article on behalf of someone else, but we can probably just scrap that and use `created_by` from `BasisModel`. 

If anything `author` should be a text field, so that you can set a non-user author like Hovedstyret or readme. If so it should be optional, and the frontend should fall back to using `created_by` if it isn't set.

**Comment by ivarnakken** [comment]
This has been implemented some time ago
